// mandebrot_plot_mm_interconnect_1.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 23.1 991

`timescale 1 ps / 1 ps
module mandebrot_plot_mm_interconnect_1 (
		input  wire        pll_0_outclk0_clk,                                         //                                       pll_0_outclk0.clk
		input  wire        mand_total_single_sys_0_reset_reset_bridge_in_reset_reset, // mand_total_single_sys_0_reset_reset_bridge_in_reset.reset
		output wire        mand_total_single_sys_0_m0_waitrequest,                    //                          mand_total_single_sys_0_m0.waitrequest
		input  wire        mand_total_single_sys_0_m0_write,                          //                                                    .write
		input  wire [31:0] mand_total_single_sys_0_m0_writedata,                      //                                                    .writedata
		output wire [9:0]  mm_bridge_0_s0_address,                                    //                                      mm_bridge_0_s0.address
		output wire        mm_bridge_0_s0_write,                                      //                                                    .write
		output wire        mm_bridge_0_s0_read,                                       //                                                    .read
		input  wire [31:0] mm_bridge_0_s0_readdata,                                   //                                                    .readdata
		output wire [31:0] mm_bridge_0_s0_writedata,                                  //                                                    .writedata
		output wire [0:0]  mm_bridge_0_s0_burstcount,                                 //                                                    .burstcount
		output wire [3:0]  mm_bridge_0_s0_byteenable,                                 //                                                    .byteenable
		input  wire        mm_bridge_0_s0_readdatavalid,                              //                                                    .readdatavalid
		input  wire        mm_bridge_0_s0_waitrequest,                                //                                                    .waitrequest
		output wire        mm_bridge_0_s0_debugaccess                                 //                                                    .debugaccess
	);

	wire         mand_total_single_sys_0_m0_translator_avalon_universal_master_0_waitrequest;   // mm_bridge_0_s0_translator:uav_waitrequest -> mand_total_single_sys_0_m0_translator:uav_waitrequest
	wire  [31:0] mand_total_single_sys_0_m0_translator_avalon_universal_master_0_readdata;      // mm_bridge_0_s0_translator:uav_readdata -> mand_total_single_sys_0_m0_translator:uav_readdata
	wire         mand_total_single_sys_0_m0_translator_avalon_universal_master_0_debugaccess;   // mand_total_single_sys_0_m0_translator:uav_debugaccess -> mm_bridge_0_s0_translator:uav_debugaccess
	wire   [9:0] mand_total_single_sys_0_m0_translator_avalon_universal_master_0_address;       // mand_total_single_sys_0_m0_translator:uav_address -> mm_bridge_0_s0_translator:uav_address
	wire         mand_total_single_sys_0_m0_translator_avalon_universal_master_0_read;          // mand_total_single_sys_0_m0_translator:uav_read -> mm_bridge_0_s0_translator:uav_read
	wire   [3:0] mand_total_single_sys_0_m0_translator_avalon_universal_master_0_byteenable;    // mand_total_single_sys_0_m0_translator:uav_byteenable -> mm_bridge_0_s0_translator:uav_byteenable
	wire         mand_total_single_sys_0_m0_translator_avalon_universal_master_0_readdatavalid; // mm_bridge_0_s0_translator:uav_readdatavalid -> mand_total_single_sys_0_m0_translator:uav_readdatavalid
	wire         mand_total_single_sys_0_m0_translator_avalon_universal_master_0_lock;          // mand_total_single_sys_0_m0_translator:uav_lock -> mm_bridge_0_s0_translator:uav_lock
	wire         mand_total_single_sys_0_m0_translator_avalon_universal_master_0_write;         // mand_total_single_sys_0_m0_translator:uav_write -> mm_bridge_0_s0_translator:uav_write
	wire  [31:0] mand_total_single_sys_0_m0_translator_avalon_universal_master_0_writedata;     // mand_total_single_sys_0_m0_translator:uav_writedata -> mm_bridge_0_s0_translator:uav_writedata
	wire   [2:0] mand_total_single_sys_0_m0_translator_avalon_universal_master_0_burstcount;    // mand_total_single_sys_0_m0_translator:uav_burstcount -> mm_bridge_0_s0_translator:uav_burstcount

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (1),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (10),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (0),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) mand_total_single_sys_0_m0_translator (
		.clk                    (pll_0_outclk0_clk),                                                             //                       clk.clk
		.reset                  (mand_total_single_sys_0_reset_reset_bridge_in_reset_reset),                     //                     reset.reset
		.uav_address            (mand_total_single_sys_0_m0_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (mand_total_single_sys_0_m0_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (mand_total_single_sys_0_m0_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (mand_total_single_sys_0_m0_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (mand_total_single_sys_0_m0_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (mand_total_single_sys_0_m0_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (mand_total_single_sys_0_m0_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (mand_total_single_sys_0_m0_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (mand_total_single_sys_0_m0_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (mand_total_single_sys_0_m0_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (mand_total_single_sys_0_m0_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_waitrequest         (mand_total_single_sys_0_m0_waitrequest),                                        //      avalon_anti_master_0.waitrequest
		.av_write               (mand_total_single_sys_0_m0_write),                                              //                          .write
		.av_writedata           (mand_total_single_sys_0_m0_writedata),                                          //                          .writedata
		.av_address             (1'b0),                                                                          //               (terminated)
		.av_burstcount          (1'b1),                                                                          //               (terminated)
		.av_byteenable          (4'b1111),                                                                       //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                                          //               (terminated)
		.av_begintransfer       (1'b0),                                                                          //               (terminated)
		.av_chipselect          (1'b0),                                                                          //               (terminated)
		.av_read                (1'b0),                                                                          //               (terminated)
		.av_readdata            (),                                                                              //               (terminated)
		.av_readdatavalid       (),                                                                              //               (terminated)
		.av_lock                (1'b0),                                                                          //               (terminated)
		.av_debugaccess         (1'b0),                                                                          //               (terminated)
		.uav_clken              (),                                                                              //               (terminated)
		.av_clken               (1'b1),                                                                          //               (terminated)
		.uav_response           (2'b00),                                                                         //               (terminated)
		.av_response            (),                                                                              //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                                          //               (terminated)
		.av_writeresponsevalid  ()                                                                               //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (10),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (10),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (1),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (1),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (0),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) mm_bridge_0_s0_translator (
		.clk                    (pll_0_outclk0_clk),                                                             //                      clk.clk
		.reset                  (mand_total_single_sys_0_reset_reset_bridge_in_reset_reset),                     //                    reset.reset
		.uav_address            (mand_total_single_sys_0_m0_translator_avalon_universal_master_0_address),       // avalon_universal_slave_0.address
		.uav_burstcount         (mand_total_single_sys_0_m0_translator_avalon_universal_master_0_burstcount),    //                         .burstcount
		.uav_read               (mand_total_single_sys_0_m0_translator_avalon_universal_master_0_read),          //                         .read
		.uav_write              (mand_total_single_sys_0_m0_translator_avalon_universal_master_0_write),         //                         .write
		.uav_waitrequest        (mand_total_single_sys_0_m0_translator_avalon_universal_master_0_waitrequest),   //                         .waitrequest
		.uav_readdatavalid      (mand_total_single_sys_0_m0_translator_avalon_universal_master_0_readdatavalid), //                         .readdatavalid
		.uav_byteenable         (mand_total_single_sys_0_m0_translator_avalon_universal_master_0_byteenable),    //                         .byteenable
		.uav_readdata           (mand_total_single_sys_0_m0_translator_avalon_universal_master_0_readdata),      //                         .readdata
		.uav_writedata          (mand_total_single_sys_0_m0_translator_avalon_universal_master_0_writedata),     //                         .writedata
		.uav_lock               (mand_total_single_sys_0_m0_translator_avalon_universal_master_0_lock),          //                         .lock
		.uav_debugaccess        (mand_total_single_sys_0_m0_translator_avalon_universal_master_0_debugaccess),   //                         .debugaccess
		.av_address             (mm_bridge_0_s0_address),                                                        //      avalon_anti_slave_0.address
		.av_write               (mm_bridge_0_s0_write),                                                          //                         .write
		.av_read                (mm_bridge_0_s0_read),                                                           //                         .read
		.av_readdata            (mm_bridge_0_s0_readdata),                                                       //                         .readdata
		.av_writedata           (mm_bridge_0_s0_writedata),                                                      //                         .writedata
		.av_burstcount          (mm_bridge_0_s0_burstcount),                                                     //                         .burstcount
		.av_byteenable          (mm_bridge_0_s0_byteenable),                                                     //                         .byteenable
		.av_readdatavalid       (mm_bridge_0_s0_readdatavalid),                                                  //                         .readdatavalid
		.av_waitrequest         (mm_bridge_0_s0_waitrequest),                                                    //                         .waitrequest
		.av_debugaccess         (mm_bridge_0_s0_debugaccess),                                                    //                         .debugaccess
		.av_begintransfer       (),                                                                              //              (terminated)
		.av_beginbursttransfer  (),                                                                              //              (terminated)
		.av_writebyteenable     (),                                                                              //              (terminated)
		.av_lock                (),                                                                              //              (terminated)
		.av_chipselect          (),                                                                              //              (terminated)
		.av_clken               (),                                                                              //              (terminated)
		.uav_clken              (1'b0),                                                                          //              (terminated)
		.av_outputenable        (),                                                                              //              (terminated)
		.uav_response           (),                                                                              //              (terminated)
		.av_response            (2'b00),                                                                         //              (terminated)
		.uav_writeresponsevalid (),                                                                              //              (terminated)
		.av_writeresponsevalid  (1'b0)                                                                           //              (terminated)
	);

endmodule
